# Generated by Django 5.0.1 on 2024-01-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Record',
        ),
    ]
